// Package api defines art's **wire-level data contract** (DTOs).
//
// Frozen by convention: every type and JSON tag in this package is the one
// contract shared by the Go side, the CLI's --json output, and the frontend
// TypeScript types. No work package may change this package's field names,
// types, or tags; a change here has to go through the architecture layer and
// be kept in sync with docs/blueprint.md and web/src/lib/types.ts.
//
// This package depends on no other internal package and contains no logic,
// only types.
package api

import "time"

// ---------------------------------------------------------------------------
// Enum constants
// ---------------------------------------------------------------------------

// Document types.
const (
	DocTypeMD   = "md"
	DocTypeHTML = "html"
)

// Thread status. The current state after folding.
const (
	StatusOpen      = "open"
	StatusAddressed = "addressed"
	StatusResolved  = "resolved"
)

// Anchor kinds.
const (
	AnchorText    = "text"    // md body text anchor (TextQuote + TextPosition)
	AnchorElement = "element" // html element anchor (data-aid, optional quote)
)

// OrphanHint is the fixed hint shown to an agent for an orphaned thread
// (design doc §7; the wording itself must not be changed).
const OrphanHint = "The anchored text no longer exists — the feedback was likely addressed. Confirm with resolve, or re-anchor."

// ---------------------------------------------------------------------------
// Documents
// ---------------------------------------------------------------------------

// Doc is an artifact's summary information, used by the index page and
// `artx list`.
type Doc struct {
	ID         string    `json:"id"`       // 6-character base36 doc id, its identity
	Slug       string    `json:"slug"`     // directory name within the vault
	Title      string    `json:"title"`    // md frontmatter title or first h1; html takes <title>
	Type       string    `json:"type"`     // DocTypeMD | DocTypeHTML
	Path       string    `json:"path"`     // absolute path (to index.md / index.html)
	RelPath    string    `json:"rel_path"` // path relative to the vault root
	URL        string    `json:"url"`      // http://host:port/a/{id}
	Rev        string    `json:"rev"`      // short sha of the most recent commit touching this file; "" if untracked
	ModTime    time.Time `json:"mod_time"`
	Size       int64     `json:"size"`
	OpenCount  int       `json:"open_count"`  // number of open threads
	TotalCount int       `json:"total_count"` // total threads (including resolved, excluding archived)
}

// DocDetail carries everything a document page needs.
//
// Rendering red line: the HTML for md is generated by Go-side goldmark and
// carried in the HTML field; the frontend only does dangerouslySetInnerHTML
// plus overlays — it must **never** re-render markdown itself.
type DocDetail struct {
	Doc

	// md-only fields.
	HTML        string         `json:"html,omitempty"`        // rendered HTML; block elements carry data-sourcepos="start:end"
	BodyOffset  int            `json:"body_offset,omitempty"` // byte offset where the body starts (after frontmatter); all sourcepos values are file-absolute
	Frontmatter map[string]any `json:"frontmatter,omitempty"` // parsed frontmatter
	HasMermaid  bool           `json:"has_mermaid,omitempty"` // contains a ```mermaid code block; frontend lazy-loads mermaid on demand
	HasMath     bool           `json:"has_math,omitempty"`    // contains $ / $$; frontend lazy-loads katex on demand

	// html-only fields.
	RawURL string `json:"raw_url,omitempty"` // iframe src, of the form /raw/{id}/

	// Historical version viewing (?v=sha). Empty means the current working copy.
	Rev0 string `json:"rev0,omitempty"`
}

// DocsResponse is the response body for GET /api/docs.
type DocsResponse struct {
	Vault string `json:"vault"` // vault name (registry key); the directory name if unregistered
	Root  string `json:"root"`  // absolute vault path
	Docs  []Doc  `json:"docs"`
}

// ---------------------------------------------------------------------------
// Version diff
// ---------------------------------------------------------------------------

// Diff operations for md blocks and html elements.
const (
	DiffUnchanged = "unchanged" // md block present in both versions with identical content
	DiffModified  = "modified"  // md block kept its place but its content was edited
	DiffAdded     = "added"     // only in the new version
	DiffRemoved   = "removed"   // only in the old version
	DiffChanged   = "changed"   // html element kept its data-aid but its own content changed
)

// Diff hunk line operations.
const (
	DiffLineCtx = "ctx"
	DiffLineDel = "del"
	DiffLineAdd = "add"
)

// DiffBlock is the fate of one md top-level block between two versions.
// From/To are [start,end) **file-absolute byte ranges** in the old/new
// source; To doubles as the join key against the new version's rendered
// data-sourcepos. Blocks are listed in new-document order, with each removed
// block already inserted before its original successor — the frontend never
// has to re-sort.
type DiffBlock struct {
	Op           string   `json:"op"`                      // DiffUnchanged | DiffModified | DiffAdded | DiffRemoved
	From         []int    `json:"from,omitempty"`          // range in the old source; modified/removed only
	To           []int    `json:"to,omitempty"`            // range in the new source; absent for removed
	AddedTexts   []string `json:"added_texts,omitempty"`   // modified only: inserted source-text segments
	RemovedTexts []string `json:"removed_texts,omitempty"` // modified only: deleted source-text segments
	HTML         string   `json:"html,omitempty"`          // removed only: the block rendered against the old version
}

// DiffElement is the fate of one html element (identified by its stable
// data-aid) between two versions. Unchanged elements are not listed.
type DiffElement struct {
	Op   string `json:"op"`             // DiffChanged | DiffAdded | DiffRemoved
	AID  string `json:"aid"`            // the element's data-aid
	HTML string `json:"html,omitempty"` // removed only: the element's old outerHTML, for the "deleted elements" sidebar
}

// DiffLine is one line of a unified hunk.
type DiffLine struct {
	Op   string `json:"op"` // DiffLineCtx | DiffLineDel | DiffLineAdd
	Text string `json:"text"`
}

// DiffHunk is a unified-diff hunk over the raw source (3 context lines),
// shared by md and html documents for the source view.
type DiffHunk struct {
	FromStart int        `json:"from_start"` // 1-based first line in the old source
	FromCount int        `json:"from_count"`
	ToStart   int        `json:"to_start"` // 1-based first line in the new source
	ToCount   int        `json:"to_count"`
	Lines     []DiffLine `json:"lines"`
}

// DiffStats aggregates a diff for the toolbar. For html documents, Modified
// counts DiffChanged elements.
type DiffStats struct {
	Added    int `json:"added"`
	Removed  int `json:"removed"`
	Modified int `json:"modified"`
}

// DiffResponse is the response body for
// GET /api/docs/{id}/diff?from=<sha>[&to=<sha>].
type DiffResponse struct {
	Doc  string `json:"doc"`
	Type string `json:"type"` // DocTypeMD | DocTypeHTML
	From string `json:"from"` // old revision, echoed exactly as the caller passed it (any git rev)
	To   string `json:"to"`   // new revision, echoed as passed; "" means the working copy

	Blocks   []DiffBlock   `json:"blocks,omitempty"`   // md only
	Elements []DiffElement `json:"elements,omitempty"` // html only

	Hunks []DiffHunk `json:"hunks"` // unified source view, both types
	Stats DiffStats  `json:"stats"`

	FrontmatterChanged bool `json:"frontmatter_changed,omitempty"` // md only; Blocks covers the body alone
	ChromeChanged      bool `json:"chrome_changed,omitempty"`      // html only: head/style/script changed, element ops don't cover it
}

// ---------------------------------------------------------------------------
// Comment threads
// ---------------------------------------------------------------------------

// ThreadAnchor is a thread anchor's **presentation form**: the create
// event's anchor with the latest remap/orphan event applied on top, with the
// Line and Context fields filled in by the anchor package.
type ThreadAnchor struct {
	Kind      string `json:"kind"`                 // AnchorText | AnchorElement
	Exact     string `json:"exact,omitempty"`      // anchored text (source file excerpt)
	Prefix    string `json:"prefix,omitempty"`     // ~32 characters before Exact
	Suffix    string `json:"suffix,omitempty"`     // ~32 characters after Exact
	Start     int    `json:"start"`                // current byte offset (file-absolute), inclusive
	End       int    `json:"end"`                  // current byte offset, exclusive
	Line      int    `json:"line"`                 // 1-based line number of Start; derived field
	Context   string `json:"context,omitempty"`    // surrounding 2 lines of original text on each side; derived field
	AID       string `json:"aid,omitempty"`        // element anchor: the target element's data-aid
	Rev       string `json:"rev,omitempty"`        // git rev this offset corresponds to
	Approx    bool   `json:"approx,omitempty"`     // true = fell back to block-level anchoring, not an exact quote hit
	Orphan    bool   `json:"orphan,omitempty"`     // true = the anchored text no longer exists
	LastExact string `json:"last_exact,omitempty"` // preserves "what this used to point at" when orphaned
}

// Reply is a single reply within a thread.
type Reply struct {
	ID        string     `json:"id"`     // <thread>.<3-character base36>
	Author    string     `json:"author"` // e.g. cappu | agent:claude | artx-web <reviewer>
	Body      string     `json:"body"`
	CreatedAt time.Time  `json:"created_at"`
	EditedAt  *time.Time `json:"edited_at,omitempty"`
}

// Addressed records an agent's "handled this" declaration.
type Addressed struct {
	By     string    `json:"by"`
	Commit string    `json:"commit,omitempty"`
	Note   string    `json:"note,omitempty"`
	At     time.Time `json:"at"`
}

// Thread is a thread's current state after folding all of its events. It is
// the **same** output shape used by both `artx comments --json` and
// GET /api/docs/{id}/comments.
type Thread struct {
	Thread     string       `json:"thread"` // thread id, e.g. c7k2f9
	Doc        string       `json:"doc"`    // doc id
	Slug       string       `json:"slug"`   // convenient for an agent to locate the document
	Path       string       `json:"path"`   // absolute path to the document
	Status     string       `json:"status"` // StatusOpen | StatusAddressed | StatusResolved
	Author     string       `json:"author"` // who raised it
	Body       string       `json:"body"`   // root comment body (after collapsing the edit chain)
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"` // ts of this thread's most recent event
	EditedAt   *time.Time   `json:"edited_at,omitempty"`
	CreatedRev string       `json:"created_rev,omitempty"`
	Anchor     ThreadAnchor `json:"anchor"`
	Replies    []Reply      `json:"replies"`
	Addressed  *Addressed   `json:"addressed,omitempty"`
	Hint       string       `json:"hint,omitempty"` // set to OrphanHint when orphaned
}

// CommentsResponse is the response body for GET /api/docs/{id}/comments.
type CommentsResponse struct {
	Doc      string   `json:"doc"`
	Threads  []Thread `json:"threads"`
	Warnings []string `json:"warnings,omitempty"` // parse warnings: corrupt blocks, orphaned events, etc.
}

// ---------------------------------------------------------------------------
// Write requests
// ---------------------------------------------------------------------------

// SelectionInput is the browser's raw description of an md selection.
//
// Key contract: the frontend does **not** compute source-file offsets
// itself. It only reports the start/end offsets of the "nearest block
// carrying data-sourcepos", the selected rendered text, and the rendered
// text immediately surrounding it within that block; the Go side then
// quote-matches within that block's source (exact match first, falling back
// to bitap fuzzy matching) to compute the final Anchor. When matching fails,
// it falls back to anchoring the whole block and sets Anchor.Approx=true.
type SelectionInput struct {
	BlockStart int    `json:"block_start"` // the start of data-sourcepos
	BlockEnd   int    `json:"block_end"`   // the end of data-sourcepos
	Exact      string `json:"exact"`       // the selected rendered text (may differ from source due to stripped md markup)
	Before     string `json:"before"`      // up to 64 characters of rendered text before the selection, within the same block
	After      string `json:"after"`       // up to 64 characters of rendered text after the selection, within the same block
}

// ElementInput is the raw description of an html artifact element anchor.
type ElementInput struct {
	AID   string `json:"aid"`             // the target element's data-aid
	Quote string `json:"quote,omitempty"` // optional selected text within the element, for refinement
}

// EventRequest is the request body for POST /api/docs/{id}/events.
// Type determines which fields are required; see blueprint.md's "HTTP API
// contract" section.
type EventRequest struct {
	Type      string          `json:"type"`                // create|reply|edit|addressed|resolve|reopen
	Thread    string          `json:"thread,omitempty"`    // required for everything except create
	Target    string          `json:"target,omitempty"`    // required for edit: a thread id or reply id
	Body      string          `json:"body,omitempty"`      // required for create/reply/edit
	Author    string          `json:"author,omitempty"`    // filled in by the server's identity rules when omitted
	Commit    string          `json:"commit,omitempty"`    // optional for addressed
	Note      string          `json:"note,omitempty"`      // optional for addressed/reopen
	Selection *SelectionInput `json:"selection,omitempty"` // required for create on an md document
	Element   *ElementInput   `json:"element,omitempty"`   // required for create on an html document
}

// EventResponse is the response body for POST /api/docs/{id}/events.
type EventResponse struct {
	OK      string `json:"ok"`               // always "ok"
	Thread  string `json:"thread"`           // the affected thread id (the newly assigned id for create)
	EventID string `json:"event_id"`         // the event id
	Status  string `json:"status,omitempty"` // the thread's new status after folding
}

// ---------------------------------------------------------------------------
// Other endpoints
// ---------------------------------------------------------------------------

// NewDocResponse is the output of `artx new --json`, and also the response
// body for POST /api/docs.
type NewDocResponse struct {
	ID   string `json:"id"`
	Path string `json:"path"`
	URL  string `json:"url"`
	Slug string `json:"slug"`
	Type string `json:"type"`
}

// NewDocRequest is the request body for POST /api/docs.
type NewDocRequest struct {
	Slug  string `json:"slug"`
	Type  string `json:"type"`
	Title string `json:"title,omitempty"`
}

// HealthResponse is the response body for GET /api/health. The CLI uses it
// to confirm that the serve instance it detected belongs to the same vault.
type HealthResponse struct {
	OK      string `json:"ok"`      // always "ok"
	Version string `json:"version"` // art's version
	Vault   string `json:"vault"`   // vault name
	Root    string `json:"root"`    // absolute vault path
	Watch   bool   `json:"watch"`   // whether the watcher is enabled
}

// CompactRequest is the request body for POST /api/compact; an empty Doc
// means all documents.
type CompactRequest struct {
	Doc   string `json:"doc,omitempty"`
	Force bool   `json:"force,omitempty"` // ignore the threshold and compact regardless
}

// CompactStat is the compaction result for a single document.
type CompactStat struct {
	Doc             string `json:"doc"`
	EventsBefore    int    `json:"events_before"`
	EventsAfter     int    `json:"events_after"`
	ThreadsArchived int    `json:"threads_archived"`
	BytesBefore     int64  `json:"bytes_before"`
	BytesAfter      int64  `json:"bytes_after"`
	Skipped         bool   `json:"skipped,omitempty"` // below threshold and not forced
}

// CompactResponse is the output of both POST /api/compact and
// `artx compact --json`.
type CompactResponse struct {
	Stats  []CompactStat `json:"stats"`
	Commit string        `json:"commit,omitempty"` // sha of the git commit compaction produced
}

// ErrorResponse is the uniform response body for all 4xx/5xx responses.
type ErrorResponse struct {
	Error   string `json:"error"`   // machine-readable error code, see blueprint.md
	Message string `json:"message"` // human-readable explanation
	Detail  string `json:"detail,omitempty"`
}

// Standard error codes. See blueprint.md for the HTTP status / CLI exit code mapping.
const (
	ErrNotFound     = "not_found"    // 404 / exit 2
	ErrBadRequest   = "bad_request"  // 400 / exit 1
	ErrUnauthorized = "unauthorized" // 401 / exit 1
	ErrForbidden    = "forbidden"    // 403 / exit 1
	ErrConflict     = "conflict"     // 409 / exit 1
	ErrInternal     = "internal"     // 500 / exit 1
)

// ---------------------------------------------------------------------------
// SSE
// ---------------------------------------------------------------------------

// SSE event names. The data payload is always the JSON of the corresponding
// struct below.
const (
	SSEComments = "comments" // a document's comments changed
	SSEDoc      = "doc"      // a document's content changed (including remap / aid injection / auto-commit)
	SSEDocs     = "docs"     // the document list gained or lost an entry
	SSEPing     = "ping"     // heartbeat, once every 25s, data is {}
)

// SSEComment is the data payload of an SSEComments event.
type SSEComment struct {
	Doc     string   `json:"doc"`
	Threads []string `json:"threads,omitempty"` // affected thread ids; empty means invalidate everything
	Rev     string   `json:"rev,omitempty"`
}

// SSEDocChange is the data payload of an SSEDoc event.
type SSEDocChange struct {
	Doc     string `json:"doc"`
	Kind    string `json:"kind"`             // content | remap | aid | remove
	Rev     string `json:"rev,omitempty"`    // new sha after auto-commit
	Remaps  int    `json:"remaps,omitempty"` // number of threads remapped this round
	Orphans int    `json:"orphans,omitempty"`
}
